# CRAN
install.packages("tidyverse")
install.packages("devtools")
install.packages("ggthemes")
install.packages("bookdown")
install.packages("rmarkdown")
install.packages("data.table")
install.packages("survey")
install.packages("ggswissmaps")
install.packages("ggvis")
install.packages("cem")
install.packages("MatchIt")
install.packages("maps")
install.packages("maptools")
install.packages("microbenchmark")
install.packages("plotly")
install.packages("RCurl")
install.packages("rgdal")
install.packages("rgeos")
install.packages("rgdal")
install.packages("RGraphics")
install.packages("rjson")
install.packages("RJSONIO")
install.packages("RODBC")
install.packages("roxygen2")
install.packages("RSQLite")
install.packages("scatterplot3d")
install.packages("sem")
install.packages("SimComp")
install.packages("spatstat")
install.packages("sqldf")
install.packages("tables")
install.packages("tm")
install.packages("XML")
install.packages("yhatr")
install.packages("pxR")
install.packages("MonetDBLite")


# github
library(devtools)
install_github("gibonet/comuniTI")
install_github("gibonet/decr")
install_github("gibonet/gibr")
install_github("gibonet/tidy2spatial")
install_github("gibonet/tidy2px")
install_github("gibonet/distrr")

install_github("hadley/pkgdown")
install_github("hadley/pkgdown")
install_github("cpsievert/staticdocs")